import { AnalyticsSummary } from "@/components/admin/analytics/AnalyticsSummary";
import { BrandAnalytics } from "@/components/admin/analytics/BrandAnalytics";
import { FeedbackAnalytics } from "@/components/admin/analytics/FeedbackAnalytics";
import { RecommendationAnalytics } from "@/components/admin/analytics/RecommendationAnalytics";
import { WeatherAnalytics } from "@/components/admin/analytics/WeatherAnalytics";
import { requireAdmin } from "@/lib/auth";
import { getCurrentRecommendationEngineMetadata } from "@/lib/engine/versioning/versionMetadata";
import { getAdminAnalyticsDashboard } from "@/services/analyticsServerService";

export const runtime = "nodejs";

export default async function AdminAnalyticsPage() {
    await requireAdmin();
    const [analytics, versionMetadata] = await Promise.all([
        getAdminAnalyticsDashboard(),
        Promise.resolve(getCurrentRecommendationEngineMetadata()),
    ]);

    return (
        <main className="min-h-screen bg-slate-50 px-4 py-8 md:px-8">
            <div className="mx-auto max-w-7xl space-y-8">
                <section className="space-y-3">
                    <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">Admin analytics</p>
                    <h1 className="text-4xl font-semibold tracking-tight text-slate-950">Recommendation platform insights</h1>
                    <p className="max-w-3xl text-muted-foreground">
                        Aggregated platform observability for recommendation generation, saved kits, feedback, weather context, workout patterns, and engine version audits.
                    </p>
                    <p className="text-sm text-slate-600">
                        Recommendation generated by Engine v{versionMetadata.version}: {versionMetadata.description}
                    </p>
                </section>

                <AnalyticsSummary summary={analytics.summary} engineVersions={analytics.engineVersions} />
                <BrandAnalytics brands={analytics.brands} />
                <WeatherAnalytics weather={analytics.weather} />
                <RecommendationAnalytics workouts={analytics.workouts} />
                <FeedbackAnalytics feedback={analytics.feedback} />
            </div>
        </main>
    );
}