export {
    CATEGORY_IMPORTANCE_WEIGHTS,
    CONDITION_SCORING_WEIGHTS,
    HOT_WEATHER_TAGS,
    LAYERING_TAGS,
    OUTFIT_RULES,
    RAIN_TAGS,
    WEATHER_THRESHOLDS,
    WIND_TAGS,
} from "./weatherRules";
export { BRAND_MULTIPLIERS, BRAND_SCORE_LIMITS } from "./brandConfig";