export type WeatherCondition = "hot" | "warm" | "cold" | "rain" | "humid" | "wind";
export type Intensity = "recovery" | "easy" | "long-run" | "tempo" | "race";
export type Terrain = "road" | "trail" | "treadmill";
export type Season = "winter" | "summer" | "shoulder";
export type Category = "top" | "bottom" | "accessory" | "outerwear" | "socks" | "hat" | "gloves";
export type RecommendationUserInput = { userId?: string; weather?: WeatherCondition; intensity?: Intensity, workoutType?: string, terrain?: Terrain; category?: Category | "all"; };
export type GenderPreference = "male" | "men" | "female" | "women" | "non_binary" | "prefer_not_to_say" |"unisex";
export type UserPreferenceInput = { genderPreference?: GenderPreference | string; favoriteBrands?: string[]; preferredBrands?: string[]; avoidedBrands?: string[]; budgetRange?: "budget" | "mid" | "premium"; budgetSensitivity?: "low" | "medium" | "high"; heatSensitivity?: string; heatTolerance?: "low" | "medium" | "high" | string; coldTolerance?: "low" | "medium" | "high" | string; terrainPreference?: "road" | "trail" | "mixed" | string; cushionPreference?: "minimalist" | "max-cushion"; recentRecommendedItemIds?: string[]; frequentlySavedItemIds?: string[]; season?: Season; };
export type RecommendationGearItem = { id: string; name: string; brandId?: string | null; brandName?: string | null; genderTarget?: string | null; category?: string | null; priceRange?: string | null; tags: string[]; weatherSuitability: Partial<Record<WeatherCondition, number>> | null; };
export type RecommendationScoreBreakdown = {
  weather: number;
  intensity: number;
  terrain: number;
  seasonality: number;
  brandAffinity: number;
  brandPenalty: number;
  budget: number;
  genderAlignment: number;
  temperatureTolerance: number;
  rotationAdjustment: number;
};
export type ScoredRecommendationItem = {
  item: RecommendationGearItem;
  score: number;
  totalScore: number;
  scoreBreakdown: RecommendationScoreBreakdown;
  breakdown: RecommendationScoreBreakdown;
  reasons: string[];
  contributions: RecommendationScoreBreakdown;
  recommendationId?: string;
};